# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "babaa9dc8b6cc0bcfad19b1e0f0be081"
name = "Ghostly by Plugzy"
handle = "ghostly-by-plugzy-2025"
application_url = "https://adaptation-rec-incidents-coming.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://adaptation-rec-incidents-coming.trycloudflare.com/auth/callback", "https://adaptation-rec-incidents-coming.trycloudflare.com/auth/shopify/callback", "https://adaptation-rec-incidents-coming.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
